name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/atomist-playground/nodetest
        tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
    - name: Push
      uses: docker/build-push-action@v2
      with:
        context: ./
        push: true
        file: ./Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: |
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=Dockerfile
    - name: Scan
      uses: atomist-playground/scan-action@c36c37796b6630b855ce3350bae82a17b1d1222e
      with:
        image: 'ghcr.io/atomist-playground/nodetest:main'
